CREATE DATABASE IF NOT EXISTS my_guitar_shop;
USE my_guitar_shop;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
CREATE TABLE categories (
  categoryID INT AUTO_INCREMENT PRIMARY KEY,
  categoryName VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE products (
  productID INT AUTO_INCREMENT PRIMARY KEY,
  categoryID INT NOT NULL,
  productCode VARCHAR(20) NOT NULL UNIQUE,
  productName VARCHAR(255) NOT NULL,
  listPrice DECIMAL(10,2) NOT NULL DEFAULT 0,
  FOREIGN KEY (categoryID) REFERENCES categories(categoryID) ON DELETE CASCADE ON UPDATE CASCADE
);
