services:
  db:
    image: mysql:8.0
    container_name: db_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: my_guitar_shop
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      - db

  web:
    build:
      context: ./web
    container_name: web_php
    restart: unless-stopped
    volumes:
      - ./web/src:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: my_guitar_shop
      DB_USER: mgs_user
      DB_PASS: pa55word
    ports:
      - "8080:80"
    depends_on:
      - db

  web_122:
    build:
      context: ./web-122
    container_name: web_php_122
    restart: unless-stopped
    volumes:
      - ./web-122/src:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: my_guitar_shop
      DB_USER: mgs_user
      DB_PASS: pa55word
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
  db_data:
