services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secsite
      TZ: Asia/Ho_Chi_Minh
    command: ["--default-authentication-plugin=mysql_native_password","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql

  app:
    build: ./app
    environment:
      DB_HOST: db
      DB_NAME: secsite
      DB_USER: root
      DB_PASS: root
      HTTPS_BEHIND_PROXY: "1"
    depends_on: [db]
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx:alpine
    depends_on: [app]
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro

  phpmyadmin:
    image: phpmyadmin:5
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  dbdata:
