version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guitarshop
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: ./web
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
    ports:
      - "8082:80"

volumes:
  dbdata:
